### ISSUE TITLE
Download all tools needed before launching the exploit

### ISSUE THREAD

**Issue by jonasrosland** [cfw-guide/dsi.cfw.guide#90]
Suggestion: If you ask the user to download dumpTool and Unlaunch to their SD card before they launch the exploit, they can just follow along instead of turning off the system, swapping the SD card over to their computer and then back to the DSi, etc.
Not sure if this has been brought up before.

**Comment by Peter0x44** [comment]
Not every user will want Unlaunch, so it could be redundant for some people.

**Comment by jonasrosland** [comment]
Understandable of course, I meant more something like this:
"If you want to prep your SD card with all the tools in this tutorial (without using the Lazy downloader), make sure to download the following to your SD card before we begin:
- X
- Y
- Z"

**Comment by lifehackerhansol** [comment]
With the new `Get Started` page in https://github.com/cfw-guide/dsi.cfw.guide/pull/139, Unlaunch is now the only file downloaded after the initial SD prep, which now has dumpTool and TWiLight Menu++. So if you are not installing Unlaunch the grand total of times required to swap back and forth between console and PC is one(1). I consider this to be enough for this issue, since as mentioned earlier, not everyone will install Unlaunch. So let's keep that separate.
